name: flutter_application_1
description: Houses of Westeros Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  convert: ^3.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  leak_tracker: ^11.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/dragon_icon_no_bg.png
  fonts:
  - family: Game of Thrones
    fonts:
      - asset: assets/Game of Thrones.ttf